# 예외 (Exception)

자바에선 에러 이외에 예외라고 부르는 오류가 있다. 예외란 잘못된 사용 또는 코딩으로 인한 오류를 뜻한다.

* 일반 예외 : 컴파일러가 예외 처리 코드를 검사하는 예외이다.
* 실행 예외 : 컴파일러가 예외 처리 코드를 검사하지 않는 예외이다.

## 예외 처리 코드

예외 처리 코드는 try - catch - finally 로 이루어진다.

try 블록에서 작성한 코드가 예외 없이 정상 실행되면 catch 블록은 실행되지 않는다. 반대로 try 블록의 코드에서 예외가 발생하면
catch 블록이 실행된다.

finally는 try 블록의 예외와 상관없이 반드시 실행된다.

```
try {
        Class.forName("com.mysql.cj.jdbc.Driver");

        String url = "jdbc:mysql://localhost:3306/music";
        String user = "java";
        String password = "";

        conn = DriverManager.getConnection(url, user, password);
    } catch (Exception e) {
        e.printStackTrace();
    }
    finally {
        System.out.println("연결 시도);
    }
```
미니 프로젝트에서 가져온 코드이다. 

여기서 try 블록에서 Class.forName 메소드를 실행하는데 만약 없다면 catch 블록을 실행시킨다.
finally 블록은 반드시 실행된다.

exception의 종류는 다양한데 상속 관계로 묶여있다. 위의 Exception은 최상위 클래스이고 그 밑에 ClassNotFoundException, NullPointerException 등등 있다.

** catch의 블록이 여러 개라 할지라도 catch 블록은 단 하나만 실행된다. try 블록에서 동시 다발적으로 예외가 발생하지 않기 때문이다.

하나의 예외가 발생하면 즉시 실행을 멈추고 catch 블록으로 이동한다.

```
 public static void main(String[] args) {

        String arr[] = {"100", "abc", null, "200"};

        for (int i = 0; i < arr.length; i++) {

            try {
                int value = Integer.parseInt(arr[i]);
                System.out.println("arr[" + i + "] : " + value);
            } catch (ArrayIndexOutOfBoundsException e) {
                System.out.println("배열 인덱스가 초과됨 : " + e.getMessage());
            } catch (NullPointerException | NumberFormatException e) {
                System.out.println("데이터에 문제가 있음 : " + e.getMessage());
            }
        }
    }
```
arr의 값을 읽어드리는 코드이다. 여기서 catch 블록을 2개 뒀는데 해당되는 1개만 실행된다.

두번째 catch에서 | 을 사용했는데 이는 catch 블록으로 동일하게 예외 처리하고 싶을 경우 사용한다.

```
arr[0] : 100
데이터에 문제가 있음 : For input string: "abc"
데이터에 문제가 있음 : Cannot parse null string
arr[3] : 200
```
